### ISSUE TITLE
'Extended' files don't seem to have overlap

### ISSUE THREAD

**Issue by RobThree** [Markus-Go/ip-countryside#9]
Just a tip maybe, but the 'extended' files don't have overlap (or I'm using a wrong method to find overlap or my overlap detection is bugged).

http://ftp.ripe.net/ripe/stats/delegated-ripencc-extended-latest
http://ftp.apnic.net/pub/stats/apnic/delegated-apnic-extended-latest
http://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest
http://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-extended-latest
http://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-extended-latest

If you're interested maybe have a look at it and let me know your findings?

If my findings are correct you _should, in theory, be able to create the db much quicker (though you may still want to detect/find overlap).

**Comment by Markus-Go** [comment]
There have been overlaps in the past, at least in the ripe delegation file. Especially, if the country "EU" was used. It might be the case that there are none nowadays, but why not keep the code as a precaution.

**Comment by RobThree** [comment]
> but why not keep the code as a precaution

Ofcourse, beter safe than sorry. I just wasn't sure if you were aware of it (or maybe even if my method of detecting overlap was/is flawed).
